In [9]:
import numpy as np
import copy

In [10]:
c = np.array([62, 18, -34, -88, -97, -24, 19, -15, 31, -13, -63, 81, -3, 63, 0, 0, 0, 0, 0, 0])

# Matriz de restricciones
A = np.array([
    [-42, -35, 68, 50, 73, 64, -44, -4, 36, -45, -89, 88, 75, -44, 0, 0, 0, 0, 0, 0],
    [49, -51, 32, 73, 32, -96, 33, 20, 61, -77, 97, 4, -56, 3, 0, 0, 0, 0, 0, 0],
    [21, -26, -86, -68, 31, 1, -10, 84, 13, -62, -1, 10, 68, 96, 0, 0, 0, 0, 0, 0],
    [49, 92, -39, 66, -89, -5, 95, 55, -24, 71, 7, 14, 23, 70, 0, 0, 0, 0, 0, 0],
    [73, 61, 93, 96, 66, 99, 76, 53, 78, 55, 91, 68, 68, 54, 1, 0, 0, 0, 0, 0],
    [-29, 17, -42, 94, -60, 28, 21, 74, 99, 31, -15, 6, -29, -15, 0, 1, 0, 0, 0, 0],
    [-97, 51, -91, 41, -57, 16, 92, 81, -35, 36, 72, -6, 22, 14, 0, 0, 1, 0, 0, 0],
    [-76, 27, 17, 69, 80, -51, 5, 65, -87, 6, -72, 20, -78, 88, 0, 0, 0, -1, 0, 0],
    [69, -1, 44, 20, -81, 27, 71, -41, 85, 91, -58, 7, -41, -30, 0, 0, 0, 0, 1, 0],
    [-5, 87, -60, 15, 94, 65, 76, 69, 62, -20, -14, 68, 53, 96, 0, 0, 0, 0, 0, -1]
])

# Términos independientes de las restricciones
b = np.array([151, 124, 71, 385, 1032, 181, 140, 12, 163, 585])

In [11]:
def añadir_variables_artificiales(A, b):
    vars = []
    for v in b:
        if v >= 0:
            vars.append(1)
        else:
            vars.append(-1)
    array = np.array(vars)
    # Crear una matriz diagonal
    matriz_diagonal = np.diag(array)
    # Usamos np.hstack para apilar horizontalmente
    resultado = np.hstack((A, matriz_diagonal))
    return resultado

r = añadir_variables_artificiales(A, b)

In [12]:
""" <pseudo-codigo Todo el programa >

def simplexII (A, b, c, B_ini):
    bool_acotado = True
    n var, m eq,
    N_ini = 1..n not in B_ini
    x_i = [0...0]
    x_b = B^-1 b 
    poner x_b  en x_i segun los indices de B_ini 
    bucle iteraciones del simplex, while seguramente
        B = columna iessima de A bucle por A i s en B_ini
        An =
        cn = de c
        cb = 
        algebra lineal, calcular r, con bland miras la q
        d descens -B -1 Aq
        tethas i la variable que sale p 
        buscas q en N_ini, y p en B_ini, y las intercambias
    
        cuando acaba
        - d >= 0 no acotado 
        - costes >= 0 acaba estas en optimo, return

    return B_optima, z , bool_acotado

    
def simplexDefinitu (A,b,c):
    n variables ,m eq
    A_inicial = A + variables 1s o -1 depende de b 
    b_inicial = b 
    c_inicial = [0,0,0,0, 1,1,1]
    B_inicial = [n,n+m]
    B_ini_II, z_inicial, _ = simplexII(A_inicial,b_inicial,c_inicial,B_inicial)
    if (z_inicial != 0):
        return None,None,None,False #sera no factible
    B_optima, z , bool_acotado = simplexII(A,b,c,B_ini_II)

    return B_optima, z , bool_acotado, True (si es fatible o no)
"""

' <pseudo-codigo Todo el programa >\n\ndef simplexII (A, b, c, B_ini):\n    bool_acotado = True\n    n var, m eq,\n    N_ini = 1..n not in B_ini\n    x_i = [0...0]\n    x_b = B^-1 b \n    poner x_b  en x_i segun los indices de B_ini \n    bucle iteraciones del simplex, while seguramente\n        B = columna iessima de A bucle por A i s en B_ini\n        An =\n        cn = de c\n        cb = \n        algebra lineal, calcular r, con bland miras la q\n        d descens -B -1 Aq\n        tethas i la variable que sale p \n        buscas q en N_ini, y p en B_ini, y las intercambias\n\n        cuando acaba\n        - d >= 0 no acotado \n        - costes >= 0 acaba estas en optimo, return\n\n    return B_optima, z , bool_acotado\n\n\ndef simplexDefinitu (A,b,c):\n    n variables ,m eq\n    A_inicial = A + variables 1s o -1 depende de b \n    b_inicial = b \n    c_inicial = [0,0,0,0, 1,1,1]\n    B_inicial = [n,n+m]\n    B_ini_II, z_inicial, _ = simplexII(A_inicial,b_inicial,c_inicial,B_inicial

In [13]:
def SimplexFaseII(A, b, c, B_ini, B_indices,B_inv):
    bool_acotado = True
    m,n = A.shape
    N_ini = set(i for i in range(n) if i not in B_indices) # Antes:(n+1)
    
    x_ini = np.zeros(n)  # Crear un array de ceros en lugar de una lista
    x_b = B_inv @ b  # Multiplicación de matrices en NumPy
    x_ini[B_indices] = x_b # Asignar los valores de x_b en las posiciones correspondientes

    def actualizacion_inversa(d,inv_anterior,p):
        d = d.T.tolist()
        vector_n = np.array([[-d[i]/d[p] if i != p else -1/d[p] for i in range(len(d))]])
        e = np.identity(len(d))
        e[p] = vector_n
        e = e.T
        inversa = e @ inv_anterior 
        return inversa

    iter = 1
    while True:#####################################################################################
        print("ITERACION", iter)
        #B_indices = sorted(B_indices) no hay que ordenar por que los idices de las columnas no tienen por que estar ordenados
        B_may = A[:, B_indices] # le he cambiado el nombre porque si no era una constante
        N_ini = sorted(N_ini)
        A_n = A[:, N_ini]
        cn = np.array([c[i] for i in N_ini])
        cb = np.array([c[i] for i in B_indices])
        z = cb @ x_b
        #####B_inversa = np.linalg.inv(B_may)
        print("B_indices", B_indices)
        print("B_may", B_may)
        print("A_n", A_n)
        print("cn", cn)
        print("cb", cb)
        print("Z", z)
        print("B_inversa",B_inv)
        #costes reducidos
        r = cn - cb @ B_inv @ A_n # r corresponde a las variables de los indices N_ini
        print("coste reducido", r)
        if np.all(r >= 0):
            return B_indices, z, bool_acotado, B_may, B_inv
        i = 0
        minimo = float('inf')
        for j in range(len(r)):
            if r[j] < minimo:
                minimo = r[j]
                i = j
            #elif r[j] == minimo: # Deberiamos elegir el del indice menor pero como N_ini esta ordenado ya habriamos elegido el del menor indice
        q = N_ini[i] # variable q tiene que entrar en la base 
        print("Variable q de entrada", i, "x", q,"sale de la base N")
        #direccion de descenso 
        d_b = -B_inv @ A[:, q]
        print("direccion de descenso", d_b)
        if np.all(d_b >= 0):
            print("PL NO ACOTADO")
            bool_acotado = False
            return None, None, bool_acotado, None, None
        d = np.zeros(n)  
        d[B_indices] = d_b
        d[q] = 1
        print("d", d)
    
        p = 0
        theta = float('inf')
        for w in range(len(d_b)):
            if d_b[w] < 0:
                val = -x_b[w]/d_b[w]
                if val < theta:
                    theta, p = val, w
                elif val == theta:  # Si hay empate, elegimos el menor índice en B_indices (regla de Blant)
                    if B_indices[w] < B_indices[p]:  
                        p = w
        print("Theta", theta)
        print("Variable de salida p", p, "X", B_indices[p], "sale de la base B")
        print("x_ini antes", x_ini)
        #Actualizaciones
        x_ini = x_ini + theta*d
        z = z + theta * r[i] 
        var_saliente, B_indices[p] = B_indices[p], q
        N_ini.remove(q) 
        N_ini.append(var_saliente)
        x_b = x_ini[B_indices]
        B_inv = actualizacion_inversa(d_b,B_inv,p)
        print("x_ini despues", x_ini)
        print("x_b", x_b)
        print("new_z", z)
        print("Variable de salida", var_saliente)
        print("B resultante", B_indices)
        print("N_ini", N_ini)
        iter += 1


In [14]:
def SimplexFaseI(A, b, c):
    m, n = A.shape #las filas son m (el numero de restr.) y n son las columnas (num de variables)
    A_inicial = añadir_variables_artificiales(A, b)
    b_inicial = b 
    c_inicial = [0]*n + [1]*m # ojo q sale vertical ! hay q trasponer??
    B_inicial = A_inicial[:,n:]
    B_inversa = B_inicial
    B_indices = list(i for i in range(n, n+m)) #antes era set para que sea mas eficiente buscar indices, pero lo cambio porque no funcionaba para seleccionar las columnas de A
    print("Fase INICIAL", A_inicial,b_inicial,c_inicial,B_inicial, B_indices)
    B_indices_II, z_inicial, f,B_ini_II, B_inversa  = SimplexFaseII(A_inicial,b_inicial,c_inicial,B_inicial, B_indices, B_inversa)
    if (z_inicial != 0):
        print("NO FACTIBLE z no es 0 despues de la fase inicial")
        return None,None,None,False #sera no factible
    print("respuesta solo fase inicial", B_indices_II, z_inicial, f,B_ini_II)
    print()
    print()
    print()
    # poner if para vigilar que no hay variables artificiales entre los indices de la base B_indices_II

    B_indices_opt, z , bool_acotado, B_optima, _ = SimplexFaseII(A,b,c,B_ini_II,B_indices_II,B_inversa)

    return B_optima, z , bool_acotado, True



Prueba del algoritmo:

In [15]:
c_prueba = [-1,-2,0,0]
A_prueba = np.array([[2,1,1,0],[1,1,0,1]])
b_prueba = np.array([3,2])
opt, zeta, acotado, bool_res = SimplexFaseI(A_prueba,b_prueba,c_prueba)
print(opt,zeta,acotado,bool_res)

Fase INICIAL [[2 1 1 0 1 0]
 [1 1 0 1 0 1]] [3 2] [0, 0, 0, 0, 1, 1] [[1 0]
 [0 1]] [4, 5]
ITERACION 1
B_indices [4, 5]
B_may [[1 0]
 [0 1]]
A_n [[2 1 1 0]
 [1 1 0 1]]
cn [0 0 0 0]
cb [1 1]
Z 5
B_inversa [[1 0]
 [0 1]]
coste reducido [-3 -2 -1 -1]
Variable q de entrada 0 x 0 sale de la base N
direccion de descenso [-2 -1]
d [ 1.  0.  0.  0. -2. -1.]
Theta 1.5
Variable de salida p 0 X 4 sale de la base B
x_ini antes [0. 0. 0. 0. 3. 2.]
x_ini despues [1.5 0.  0.  0.  0.  0.5]
x_b [1.5 0.5]
new_z 0.5
Variable de salida 4
B resultante [0, 5]
N_ini [1, 2, 3, 4]
ITERACION 2
B_indices [0, 5]
B_may [[2 0]
 [1 1]]
A_n [[1 1 0 1]
 [1 0 1 0]]
cn [0 0 0 1]
cb [0 1]
Z 0.5
B_inversa [[ 0.5  0. ]
 [-0.5  1. ]]
coste reducido [-0.5  0.5 -1.   1.5]
Variable q de entrada 2 x 3 sale de la base N
direccion de descenso [ 0. -1.]
d [ 0.  0.  0.  1.  0. -1.]
Theta 0.5
Variable de salida p 1 X 5 sale de la base B
x_ini antes [1.5 0.  0.  0.  0.  0.5]
x_ini despues [1.5 0.  0.  0.5 0.  0. ]
x_b [1.5 0.5]
new_z

In [8]:
c_prueba = [-1,-2,0,0]
A_prueba = np.array([[2,1,1,0],[1,1,0,1]])
b_prueba = np.array([3,2])
opt, zeta, acotado, bool_res = SimplexFaseI(A_prueba,b_prueba,c_prueba)
print(opt,zeta,acotado,bool_res)

Fase INICIAL [[2 1 1 0 1 0]
 [1 1 0 1 0 1]] [3 2] [0, 0, 0, 0, 1, 1] [[1 0]
 [0 1]] [4, 5]
ITERACION 1
B_indices [4, 5]
B_may [[1 0]
 [0 1]]
A_n [[2 1 1 0]
 [1 1 0 1]]
cn [0 0 0 0]
cb [1 1]
Z 5.0
B_inversa [[1. 0.]
 [0. 1.]]
coste reducido [-3. -2. -1. -1.]
Variable q de entrada 0 x 0 sale de la base N
direccion de descenso [-2. -1.]
d [ 1.  0.  0.  0. -2. -1.]
Theta 1.5
Variable de salida p 0 X 4 sale de la base B
x_ini antes [0. 0. 0. 0. 3. 2.]
x_ini despues [1.5 0.  0.  0.  0.  0.5]
x_b [1.5 0.5]
new_z 0.5
Variable de salida 4
B resultante [0, 5]
N_ini [1, 2, 3, 4]
ITERACION 2
B_indices [0, 5]
B_may [[2 0]
 [1 1]]
A_n [[1 1 0 1]
 [1 0 1 0]]
cn [0 0 0 1]
cb [0 1]
Z 0.5
B_inversa [[ 0.5  0. ]
 [-0.5  1. ]]
coste reducido [-0.5  0.5 -1.   1.5]
Variable q de entrada 2 x 3 sale de la base N
direccion de descenso [ 0. -1.]
d [ 0.  0.  0.  1.  0. -1.]
Theta 0.5
Variable de salida p 1 X 5 sale de la base B
x_ini antes [1.5 0.  0.  0.  0.  0.5]
x_ini despues [1.5 0.  0.  0.5 0.  0. ]
x_b [1.

In [81]:
opt, zeta, acotado, bool_res = SimplexFaseI(A,b,c)
print(opt,zeta,acotado,bool_res)

Fase INICIAL [[-42 -35  68  50  73  64 -44  -4  36 -45 -89  88  75 -44   0   0   0   0
    0   0   1   0   0   0   0   0   0   0   0   0]
 [ 49 -51  32  73  32 -96  33  20  61 -77  97   4 -56   3   0   0   0   0
    0   0   0   1   0   0   0   0   0   0   0   0]
 [ 21 -26 -86 -68  31   1 -10  84  13 -62  -1  10  68  96   0   0   0   0
    0   0   0   0   1   0   0   0   0   0   0   0]
 [ 49  92 -39  66 -89  -5  95  55 -24  71   7  14  23  70   0   0   0   0
    0   0   0   0   0   1   0   0   0   0   0   0]
 [ 73  61  93  96  66  99  76  53  78  55  91  68  68  54   1   0   0   0
    0   0   0   0   0   0   1   0   0   0   0   0]
 [-29  17 -42  94 -60  28  21  74  99  31 -15   6 -29 -15   0   1   0   0
    0   0   0   0   0   0   0   1   0   0   0   0]
 [-97  51 -91  41 -57  16  92  81 -35  36  72  -6  22  14   0   0   1   0
    0   0   0   0   0   0   0   0   1   0   0   0]
 [-76  27  17  69  80 -51   5  65 -87   6 -72  20 -78  88   0   0   0  -1
    0   0   0   0   0   0   0   0   0 

In [ ]:
c_ej = [-1, 0,0]
A_ej = np.array([[1, 1,1], [2, -1, 0]])
b_ej = np.array([4,2])
opt, zeta, acotado, bool_res = SimplexFaseI(A_ej,b_ej,c_ej)
print(opt,zeta,acotado,bool_res)

Fase INICIAL [[ 1  1  1  1  0]
 [ 2 -1  0  0  1]] [4 2] [0, 0, 0, 1, 1] [[1 0]
 [0 1]] [3, 4]
ITERACION 1
B_indices [3, 4]
B_may [[1 0]
 [0 1]]
A_n [[ 1  1  1]
 [ 2 -1  0]]
cn [0 0 0]
cb [1 1]
Z 6.0
B_inversa [[1. 0.]
 [0. 1.]]
coste reducido [-3.  0. -1.]
Variable q de entrada 0 x 0 sale de la base N
direccion de descenso [-1. -2.]
d [ 1.  0.  0. -1. -2.]
Theta 1.0
Variable de salida p 1 X 4 sale de la base B
x_ini antes [0. 0. 0. 4. 2.]
x_ini despues [1. 0. 0. 3. 0.]
x_b [3. 1.]
new_z 3.0
Variable de salida 4
B resultante [3, 0]
N_ini [1, 2, 4]
ITERACION 2
B_indices [3, 0]
B_may [[1 1]
 [0 2]]
A_n [[ 1  1  0]
 [-1  0  1]]
cn [0 0 1]
cb [1 0]
Z 3.0
B_inversa [[ 1.  -0.5]
 [ 0.   0.5]]
coste reducido [-1.5 -1.   1.5]
Variable q de entrada 0 x 1 sale de la base N
direccion de descenso [-1.5  0.5]
d [ 0.5  1.   0.  -1.5  0. ]
Theta 2.0
Variable de salida p 0 X 3 sale de la base B
x_ini antes [1. 0. 0. 3. 0.]
x_ini despues [2. 2. 0. 0. 0.]
x_b [2. 2.]
new_z 0.0
Variable de salida 3
B resu

In [82]:
# Vector c
c1 = np.array([-28, -4, 33, 51, -35, -51, -8, -49, 1, 3, -71, -20, -64, -68, 0, 0, 0, 0, 0, 0])

# Matriz A
A1 = np.array([
    [78, 92, 5, 49, -89, 45, -31, 64, 89, 61, 12, 6, -35, -88, 0, 0, 0, 0, 0, 0],
    [65, -100, 97, -31, 65, 64, 41, 39, -36, 64, 91, -84, -100, -40, 0, 0, 0, 0, 0, 0],
    [51, -15, -36, 56, -9, -7, 19, 67, -23, 88, -2, 93, -74, -38, 0, 0, 0, 0, 0, 0],
    [-25, -16, 11, 88, 70, -69, -19, -8, 63, -6, 19, -98, 75, -30, 0, 0, 0, 0, 0, 0],
    [74, 67, 53, 55, 90, 96, 76, 68, 68, 70, 86, 84, 94, 97, 1, 0, 0, 0, 0, 0],
    [-54, 6, -72, 65, 71, 12, 0, -62, -60, 56, 82, 81, -83, -6, 0, 1, 0, 0, 0, 0],
    [59, 48, -16, 61, -65, -58, -3, -46, 80, 74, 74, 74, -8, 1, 0, 0, 1, 0, 0, 0],
    [-42, 97, -53, -74, 55, -5, 10, -99, 58, -44, 47, 66, 0, -4, 0, 0, 0, -1, 0, 0],
    [-25, 20, 57, 45, 56, 90, -6, -73, -76, 95, 67, -27, -30, -65, 0, 0, 0, 0, -1, 0],
    [98, 80, -58, 81, -4, -13, -24, -24, 7, -71, 38, 44, 71, -69, 0, 0, 0, 0, 0, -1]
])

# Vector b
b1 = np.array([258, 135, 170, 55, 1079, 37, 276, 11, 127, 155])

opt, zeta, acotado, bool_res = SimplexFaseI(A1,b1,c1)
print(opt,zeta,acotado,bool_res)

Fase INICIAL [[  78   92    5   49  -89   45  -31   64   89   61   12    6  -35  -88
     0    0    0    0    0    0    1    0    0    0    0    0    0    0
     0    0]
 [  65 -100   97  -31   65   64   41   39  -36   64   91  -84 -100  -40
     0    0    0    0    0    0    0    1    0    0    0    0    0    0
     0    0]
 [  51  -15  -36   56   -9   -7   19   67  -23   88   -2   93  -74  -38
     0    0    0    0    0    0    0    0    1    0    0    0    0    0
     0    0]
 [ -25  -16   11   88   70  -69  -19   -8   63   -6   19  -98   75  -30
     0    0    0    0    0    0    0    0    0    1    0    0    0    0
     0    0]
 [  74   67   53   55   90   96   76   68   68   70   86   84   94   97
     1    0    0    0    0    0    0    0    0    0    1    0    0    0
     0    0]
 [ -54    6  -72   65   71   12    0  -62  -60   56   82   81  -83   -6
     0    1    0    0    0    0    0    0    0    0    0    1    0    0
     0    0]
 [  59   48  -16   61  -65  -58   -3  -46   8

In [87]:
c2 = np.array([83, -62, -65, -49, 27, -78, -73, -83, -29, -17, -43, 42, 76, 2, 0, 0, 0, 0, 0, 0])

# Matriz A
A2 = np.array([
    [3, -8, -66, 27, -45, 0, -47, 99, -5, 66, 71, -64, 86, 51, 0, 0, 0, 0, 0, 0],
    [16, 93, -5, 88, -56, 81, 28, 10, 43, -12, 98, 14, -54, 1, 0, 0, 0, 0, 0, 0],
    [-82, 36, 45, 61, -50, -90, -38, 32, 8, -21, 50, 84, -6, 80, 0, 0, 0, 0, 0, 0],
    [-28, 18, 72, -86, -13, 91, 37, 15, 91, 98, 69, -97, -2, 20, 0, 0, 0, 0, 0, 0],
    [19, -50, 39, 61, -23, -16, -35, 68, 18, 51, 56, -13, -69, 81, 1, 0, 0, 0, 0, 0],
    [-84, 42, -73, -57, 91, -50, -32, 47, 86, -59, 35, 21, 48, 53, 0, -1, 0, 0, 0, 0],
    [52, 39, 22, -49, -36, -39, 67, 32, 48, 77, 66, -51, -2, -94, 0, 0, 1, 0, 0, 0],
    [66, 91, 0, 14, 4, 56, 35, 15, 15, 10, 20, 63, 73, 57, 0, 0, 0, 1, 0, 0],
    [27, 21, 98, 38, 23, 33, 91, 38, 59, 69, 21, 53, 87, 41, 0, 0, 0, 0, 1, 0],
    [5, 69, 83, 55, 12, 68, 25, 28, 28, 62, 14, 27, 87, 53, 0, 0, 0, 0, 0, 1]
])

# Vector b
b2 = np.array([168, 345, 109, 285, 188, 67, 133, 30, 80, 62])
opt, zeta, acotado, bool_res = SimplexFaseI(A2,b2,c2)
print(opt,zeta,acotado,bool_res)

Fase INICIAL [[  3  -8 -66  27 -45   0 -47  99  -5  66  71 -64  86  51   0   0   0   0
    0   0   1   0   0   0   0   0   0   0   0   0]
 [ 16  93  -5  88 -56  81  28  10  43 -12  98  14 -54   1   0   0   0   0
    0   0   0   1   0   0   0   0   0   0   0   0]
 [-82  36  45  61 -50 -90 -38  32   8 -21  50  84  -6  80   0   0   0   0
    0   0   0   0   1   0   0   0   0   0   0   0]
 [-28  18  72 -86 -13  91  37  15  91  98  69 -97  -2  20   0   0   0   0
    0   0   0   0   0   1   0   0   0   0   0   0]
 [ 19 -50  39  61 -23 -16 -35  68  18  51  56 -13 -69  81   1   0   0   0
    0   0   0   0   0   0   1   0   0   0   0   0]
 [-84  42 -73 -57  91 -50 -32  47  86 -59  35  21  48  53   0  -1   0   0
    0   0   0   0   0   0   0   1   0   0   0   0]
 [ 52  39  22 -49 -36 -39  67  32  48  77  66 -51  -2 -94   0   0   1   0
    0   0   0   0   0   0   0   0   1   0   0   0]
 [ 66  91   0  14   4  56  35  15  15  10  20  63  73  57   0   0   0   1
    0   0   0   0   0   0   0   0   0 

In [89]:
# Vector c
c3 = np.array([-86, -76, -64, -49, -36, -49, -1, -79, -82, -99, 0, -95, -18, -95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Matriz A
A3 = np.array([
    [28, 49, 53, 65, 75, 50, 64, 50, 98, 10, 79, 64, 46, 80, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [27, 36, 66, 90, 88, 88, 15, 35, 52, 26, 81, 5, 54, 96, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [26, 85, 0, 20, 53, 45, 20, 99, 74, 97, 24, 66, 52, 34, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    [2, 38, 1, 93, 58, 17, 23, 93, 30, 65, 6, 73, 96, 65, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0],
    [83, 96, 5, 3, 98, 15, 34, 70, 73, 5, 1, 86, 8, 49, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0],
    [86, 31, 62, 64, 5, 14, 82, 5, 48, 60, 62, 60, 64, 88, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0],
    [31, 80, 32, 69, 27, 57, 68, 96, 33, 64, 48, 45, 65, 99, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0],
    [91, 36, 20, 98, 97, 3, 8, 67, 50, 83, 98, 46, 93, 42, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0],
    [95, 74, 60, 53, 5, 95, 12, 65, 55, 82, 50, 80, 82, 75, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0],
    [85, 75, 23, 71, 4, 84, 27, 98, 48, 72, 31, 65, 53, 98, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1]
])

# Vector b
b3 = np.array([810, 758, 694, 659, 625, 730, 813, 831, 882, 833])

opt, zeta, acotado, bool_res = SimplexFaseI(A3,b3,c3)
print(opt,zeta,acotado,bool_res)


Fase INICIAL [[28 49 53 65 75 50 64 50 98 10 79 64 46 80 -1  0  0  0  0  0  0  0  0  0
   1  0  0  0  0  0  0  0  0  0]
 [27 36 66 90 88 88 15 35 52 26 81  5 54 96  0 -1  0  0  0  0  0  0  0  0
   0  1  0  0  0  0  0  0  0  0]
 [26 85  0 20 53 45 20 99 74 97 24 66 52 34  0  0 -1  0  0  0  0  0  0  0
   0  0  1  0  0  0  0  0  0  0]
 [ 2 38  1 93 58 17 23 93 30 65  6 73 96 65  0  0  0 -1  0  0  0  0  0  0
   0  0  0  1  0  0  0  0  0  0]
 [83 96  5  3 98 15 34 70 73  5  1 86  8 49  0  0  0  0 -1  0  0  0  0  0
   0  0  0  0  1  0  0  0  0  0]
 [86 31 62 64  5 14 82  5 48 60 62 60 64 88  0  0  0  0  0 -1  0  0  0  0
   0  0  0  0  0  1  0  0  0  0]
 [31 80 32 69 27 57 68 96 33 64 48 45 65 99  0  0  0  0  0  0 -1  0  0  0
   0  0  0  0  0  0  1  0  0  0]
 [91 36 20 98 97  3  8 67 50 83 98 46 93 42  0  0  0  0  0  0  0 -1  0  0
   0  0  0  0  0  0  0  1  0  0]
 [95 74 60 53  5 95 12 65 55 82 50 80 82 75  0  0  0  0  0  0  0  0 -1  0
   0  0  0  0  0  0  0  0  1  0]
 [85 75 23 71  4 84 27 9